GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
"content": "GET and POST are the most important methods of HTsTP protocol",
"important": true
}

###
PUT http://localhost:3001/api/notes/6a10c5458212ad6d403c9e1b
Content-Type: application/json

{
"content": "GET and POST are the most important methods of HTsTP protocol",
"important": true
}